<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseDomainModel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('domain_model');
        $this->hasColumn('concept_name', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('concept_slug', 'string', 255, array('type' => 'string', 'notnull' => true, 'unique' => true, 'length' => '255'));
    }

    public function setUp()
    {
        $this->hasOne('UserModel as Concept', array('local' => 'id',
                                                    'foreign' => 'concept_id'));

        $nestedset0 = new Doctrine_Template_NestedSet();
        $this->actAs($nestedset0);
    }
}