activity_concept_activity2concept:
  class: sfDoctrineRouteCollection
  options:
    model:                ActivityConcept
    module:               activity2concept
    prefix_path:          activity2concept
    column:               activity_id
    with_wildcard_routes: true

activity_activity:
  class: sfDoctrineRouteCollection
  options:
    model:                Activity
    module:               activity
    prefix_path:          activity
    column:               id
    with_wildcard_routes: true

group_group:
  class: sfDoctrineRouteCollection
  options:
    model:                Group
    module:               group
    prefix_path:          group
    column:               id
    with_wildcard_routes: true

user_user:
  class: sfDoctrineRouteCollection
  options:
    model:                User
    module:               user
    prefix_path:          user
    column:               id
    with_wildcard_routes: true

domain_model:
  class: sfDoctrineRouteCollection
  options:
    model:                DomainModel
    module:               domain
    prefix_path:          domain
    column:               id
    with_wildcard_routes: true

# default rules
homepage:
  url:   /
  param: { module: domain, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
