default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:
    - jQuery.treeTable.css
    - main.css
    
  javascripts:
    - jquery.min.js
    - jquery-ui.min.js
    - jquery.treeTable.min.js

  has_layout:     on
  layout:         layout
