DomainModel:
  actAs:
    NestedSet:
    Sluggable:
      unique: true
      fields: [concept_name]
      alias: concept_slug
      canUpdate: true
  columns:
    concept_name: {type: string(255)}

UserModel:
  columns:
    concept_id:           {type: integer}
    user_id:              {type: integer}
    bloom_evaluation:     {type: float, default: 0.0}
    bloom_synthesis:      {type: float, default: 0.0}
    bloom_analysis:       {type: float, default: 0.0}
    bloom_application:    {type: float, default: 0.0}
    bloom_understanding:  {type: float, default: 0.0}
    bloom_knowledge:      {type: float, default: 0.0}
  relations:
    DomainModel: {onDelete: CASCADE, local: concept_id, foreign: id, foreignAlias: Concept}
    User:        {onDelete: CASCADE, local: user_id, foreign: id, foreignAlias: User}

Group:
  tableName: groups
  columns:
    name:     {type: string(255), unique: true}
  relations:
    User: {onDelete: CASCADE, class: User, refClass: UserGroup}

User:
  columns:
    username: {type: string(255), notnull: true, unique: true}
    email:    {type: string(255), unique: true}
  relations:
    Group: {onDelete: CASCADE, class: Group, refClass: UserGroup}

UserGroup:
  columns:
    user_id:  {type: integer, primary: true }
    group_id: {type: integer, primary: true }
  relations:
    Group: {onDelete: CASCADE, local: group_id, foreign: id}
    User: {onDelete: CASCADE, local: user_id, foreign: id}

Activity:
  columns:
    name:                  {type: string(255)}
    type:                  {type: enum, values: ['reading', 'exercise', 'quiz', 'worked example']}
    resource_type:         {type: enum, values: ['upload', 'external']}
    resource_uri_upload:   {type: string(255)}
    resource_uri_external: {type: string(255)}
  relations:
    DomainModel:  {onDelete: CASCADE, class: DomainModel, refClass: ActivityConcept, foreign: concept_id, local: activity_id}
    SubActivity:  {onDelete: CASCADE, class: Activity, refClass: ActivitySubActivity, foreign: child_id, local: parent_id}

ActivitySubActivity:
  columns:
    parent_id:  {type: integer, primary: true}
    child_id:   {type: integer, primary: true}

ActivityConcept:
  columns:
    activity_id:  {type: integer, primary: true }
    concept_id:   {type: integer, primary: true }
    bloom_evaluation:     {type: float, default: 0.0}
    bloom_synthesis:      {type: float, default: 0.0}
    bloom_analysis:       {type: float, default: 0.0}
    bloom_application:    {type: float, default: 0.0}
    bloom_understanding:  {type: float, default: 0.0}
    bloom_knowledge:      {type: float, default: 0.0}
  relations:
    DomainModel:  {onDelete: CASCADE, local: concept_id, foreign: id }
    Activity:     {onDelete: CASCADE, local: activity_id, foreign: id }

UserActivity:
  columns:
    user_id:      {type: integer, primary: true}
    group_id:     {type: integer}
    activity_id:  {type: integer}
    progress:     {type: integer, default: 0}