DomainModel:
  actAs:
    NestedSet:
    Sluggable:
      unique: true
      fields: [concept_name]
      alias: concept_slug
      canUpdate: true
  columns:
    concept_name: {type: string(255)}

UserModel:
  columns:
    concept_id:           {type: integer}
    user_id:              {type: integer}
    bloom_evaluation:     {type: integer}
    bloom_synthesis:      {type: integer}
    bloom_analysis:       {type: integer}
    bloom_application:    {type: integer}
    bloom_understanding:  {type: integer}
    bloom_knowledge:      {type: integer}
  relations:
    DomainModel: {onDelete: CASCADE, local: concept_id, foreign: id, foreignAlias: Concept}
    User:        {onDelete: CASCADE, local: user_id, foreign: id, foreignAlias: User}

Group:
  tableName: groups
  columns:
    name:     {type: string(255), unique: true}
  relations:
    Users: {onDelete: CASCADE, class: User, refClass: UserGroup}

User:
  columns:
    username: {type: string(255), notnull: true, unique: true}
    email:    {type: string(255), unique: true}

UserGroup:
  columns:
    user_id:  {type: integer, primary: true }
    group_id: {type: integer, primary: true }

Activity:
  columns:
    name:       {type: string(255)}
    type:       {type: enum, values: ['reading', 'exercise', 'test']}
    weight:     {type: float}
  relations:
    DomainModel: {onDelete: CASCADE, class: DomainModel, refClass: ActivityConcept, foreign: concept_id, local: activity_id}

ActivityConcept:
  columns:
    activity_id:  {type: integer, primary: true }
    concept_id:   {type: integer, primary: true }
    weight:       {type: integer}
  relations:
    DomainModel:  {onDelete: CASCADE, local: concept_id, foreign: id }
    Activity:     {onDelete: CASCADE, local: activity_id, foreign: id }
