# default rules

domain:
  url:   /domain.:sf_format
  param: { module: domain, action: index}
  requirements:
    sf_method: [get]
    sf_format: (?:html|xml)

user:
  url:  /usermodel/:id.:sf_format
  param: { module: user, action: index }
  requirements:
    sf_method: [get]
    sf_format: (?:html|xml)
