# default rules

domain:
  url:   /domain.:sf_format
  param: { module: domain, action: index}
  requirements:
    sf_method: [get]
    sf_format: (?:html|xml)

domainPart:
  url:   /domain/concept/:concept_slug.:sf_format
  param: { module: domain, action: show}
  requirements:
    sf_method: [get]
    sf_format: (?:html|xml)

domainActivity:
  url:  /domain2activity.:sf_format
  param: { module: domain, action: activity}
  requirements:
    sf_method: [get]
    sf_format: (?:html|xml)

activityDomain:
  url: /activity2domain.:sf_format
  param: { module: activity, action: index}
  requirements:
    sf_method: [get]
    sf_format: (?:html|xml)

domainUpdateBySlug:
  url:      /domain/concept/:concept_slug
  param:    { module: domain, action: update}
  class: sfDoctrineRoute
  options:  { model: DomainModel, type: object }
  requirements:
    sf_method: [put, post]
    concept_slug: \w+

userModel:
  url:  /usermodel/:username.:sf_format
  param: { module: userModel, action: index}
  requirements:
    sf_method: [get]
    sf_format: (?:xml)

userModelPart:
  url: /usermodel/:username/concept/:concept_slug.:sf_format
  param: { module: userModel, action: show}
  requirements:
    sf_method: [get]
    sf_format: (?:html|xml)

updateUserModelPart:
  url: /usermodel/:username/concept/:concept_slug
  param:
    module: userModel
    action: update
  requirements:
    sf_method: [get, put, post]

homepage:
  url:   /
  param: { module: domain, action: index, sf_format: html}