generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Activity
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          activity_activity
    with_doctrine_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        title:   Activity Management
        display: [id, name, type, resource_type, _resource_uri]
      filter:
        display: [name, type, resource_type, domain_model_list]
      form:
        class: BeActivityForm
      edit:    ~
      new:     ~
