<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Activity extends BaseActivity
{
  public function __toString()
  {
    return $this['name'];
  }

  public function isResourceExternal()
  {
    return ($this->resource_type == 'external');
  }

  public function isResourceLocal()
  {
    return !$this->isResourceExternal();
  }

  public function getResourceUri()
  {

   return !empty($this->resource_uri_upload) ? $this->resource_uri_upload : $this->resource_uri_external;
  }
}